var data = {
    tile:
    {
        a:[
            {
                lower:0,
                upper:7.5,
                value:1400
            },
            {
                lower:7.5,
                upper:12.5,
                value:1340
            },
            {
                lower:12.5,
                upper:null,
                value:1300
            },
        ],  
        b:[
            {
                lower:0,
                upper:7.5,
                value:1400
            },
            {
                lower:7.5,
                upper:12.5,
                value:1340
            },
            {
                lower:12.5,
                upper:null,
                value:1300
            },
        ],
        c:[
            {
                lower:0,
                upper:7.5,
                value:1400
            },
            {
                lower:7.5,
                upper:12.5,
                value:1340
            },
            {
                lower:12.5,
                upper:null,
                value:1300
            },
        ],
        d:[
            {
                lower:0,
                upper:null,
                value:500
            },
        ],
    },
    tin:{
        a:[
            {
                lower:0,
                upper:7.5,
                value:1400
            },
            {
                lower:7.5,
                upper:12.5,
                value:1340
            },
            {
                lower:12.5,
                upper:null,
                value:1300
            },
        ],  
        b:[
            {
                lower:0,
                upper:7.5,
                value:1400
            },
            {
                lower:7.5,
                upper:12.5,
                value:1340
            },
            {
                lower:12.5,
                upper:null,
                value:1300
            },
        ],
        c:[
            {
                lower:0,
                upper:7.5,
                value:1400
            },
            {
                lower:7.5,
                upper:12.5,
                value:1340
            },
            {
                lower:12.5,
                upper:null,
                value:1300
            },
        ],
        d:[
            {
                lower:0,
                upper:null,
                value:500
            },
        ],
    },
    flat:{
        a:[
            {
                lower:0,
                upper:7.5,
                value:1400
            },
            {
                lower:7.5,
                upper:12.5,
                value:1340
            },
            {
                lower:12.5,
                upper:null,
                value:1300
            },
        ],  
        b:[
            {
                lower:0,
                upper:7.5,
                value:1400
            },
            {
                lower:7.5,
                upper:12.5,
                value:1340
            },
            {
                lower:12.5,
                upper:null,
                value:1300
            },
        ],
        c:[
            {
                lower:0,
                upper:7.5,
                value:1400
            },
            {
                lower:7.5,
                upper:12.5,
                value:1340
            },
            {
                lower:12.5,
                upper:null,
                value:1300
            },
        ],
        d:[
            {
                lower:0,
                upper:null,
                value:500
            },
        ],
    },
};